apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  volumes:
  - name: pvol   # same
    persistentVolumeClaim:
      claimName: pvc   # e name same hona chahiye  pvc.yml ke name se
  containers:
  - image: nginx
    name: cont-one
    volumeMounts:
    - name: pvol   # same
      mountPath: /tmp/pv
    imagePullPolicy: IfNotPresent
  restartPolicy: Never
